// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sample.Donnees;

#nullable disable

namespace Sample.Migrations
{
    [DbContext(typeof(SampleContext))]
    [Migration("20260922155121_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sample.Modeles.EtatJoueur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<int>("Force")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Vie")
                        .HasColumnType("int");

                    b.Property<int>("VieMax")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EtatJoueur");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Defense = 2,
                            Force = 5,
                            Nom = "Héros",
                            Vie = 20,
                            VieMax = 20
                        });
                });

            modelBuilder.Entity("Sample.Modeles.Evenement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Degats")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Objet")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Evenements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degats = 0,
                            Description = "Un couloir humide et silencieux. Rien à signaler.",
                            Nom = "Couloir vide",
                            Type = "Rien"
                        },
                        new
                        {
                            Id = 2,
                            Degats = 0,
                            Description = "Des toiles d'araignée et un vieux tabouret. Rien d'utile.",
                            Nom = "Salle abandonnée",
                            Type = "Rien"
                        },
                        new
                        {
                            Id = 3,
                            Degats = 0,
                            Description = "Un grognement résonne : un monstre surgit de l'ombre !",
                            Nom = "Rencontre",
                            Type = "Monstre"
                        },
                        new
                        {
                            Id = 4,
                            Degats = 0,
                            Description = "Quelque chose vous attaque par derrière !",
                            Nom = "Embuscade",
                            Type = "Monstre"
                        },
                        new
                        {
                            Id = 5,
                            Degats = 4,
                            Description = "Le sol se dérobe sur des pointes rouillées.",
                            Nom = "Piège à pointes",
                            Type = "Piege"
                        },
                        new
                        {
                            Id = 6,
                            Degats = 2,
                            Description = "Une fléchette jaillit du mur.",
                            Nom = "Fléchette",
                            Type = "Piege"
                        },
                        new
                        {
                            Id = 7,
                            Degats = -6,
                            Description = "Une eau claire et scintillante. Vous vous sentez mieux.",
                            Nom = "Fontaine de santé",
                            Type = "Fontaine"
                        },
                        new
                        {
                            Id = 8,
                            Degats = 0,
                            Description = "Un petit coffre entrouvert.",
                            Nom = "Coffre",
                            Objet = "Ration",
                            Type = "Objet"
                        },
                        new
                        {
                            Id = 9,
                            Degats = 0,
                            Description = "Une arme pend au mur.",
                            Nom = "Râtelier",
                            Objet = "Épée",
                            Type = "Objet"
                        },
                        new
                        {
                            Id = 10,
                            Degats = 0,
                            Description = "Un courant d'air frais... La sortie du donjon !",
                            Nom = "Sortie",
                            Type = "Sortie"
                        });
                });

            modelBuilder.Entity("Sample.Modeles.Monstre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Attaque")
                        .HasColumnType("int");

                    b.Property<int>("Defense")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Vie")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Monstres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Attaque = 3,
                            Defense = 0,
                            Nom = "Rat géant",
                            Vie = 4
                        },
                        new
                        {
                            Id = 2,
                            Attaque = 4,
                            Defense = 1,
                            Nom = "Gobelin",
                            Vie = 7
                        },
                        new
                        {
                            Id = 3,
                            Attaque = 5,
                            Defense = 1,
                            Nom = "Squelette",
                            Vie = 9
                        },
                        new
                        {
                            Id = 4,
                            Attaque = 6,
                            Defense = 2,
                            Nom = "Orc",
                            Vie = 12
                        });
                });

            modelBuilder.Entity("Sample.Modeles.ObjetInventaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Inventaire");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Ration",
                            Quantite = 2
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Torche",
                            Quantite = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
